name: BarcodeKeyboard
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 18.0

targets:
  BarcodeKeyboard:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: App
      - path: Shared
    info:
      path: App/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLName: BarcodeKeyboard URL Scheme
            CFBundleURLSchemes:
              - barcodekb
        NSCameraUsageDescription: Potrzebujemy dostępu do aparatu, aby skanować kody kreskowe.
    entitlements:
      path: App/BarcodeKeyboard.entitlements
    settings:
      base:
        PRODUCT_NAME: BarcodeKeyboard
        PRODUCT_BUNDLE_IDENTIFIER: pl.twojefirma.klawiatura
        CODE_SIGN_ENTITLEMENTS: App/BarcodeKeyboard.entitlements
        DEVELOPMENT_TEAM: 55YFRJ3MBY
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: KeyboardExtension
        embed: true

  KeyboardExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: KeyboardExtension
      - path: Shared
    info:
      path: KeyboardExtension/Info.plist
      properties:
        CFBundleDisplayName: Klawiatura Kodów
        NSExtension:
          NSExtensionAttributes:
            IsASCIICapable: false
            PrefersRightToLeft: false
            PrimaryLanguage: pl-PL
            RequestsOpenAccess: true
          NSExtensionPointIdentifier: com.apple.keyboard-service
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).KeyboardViewController
    entitlements:
      path: KeyboardExtension/KeyboardExtension.entitlements
    settings:
      base:
        PRODUCT_NAME: KeyboardExtension
        PRODUCT_BUNDLE_IDENTIFIER: pl.twojefirma.klawiatura.KeyboardExtension
        CODE_SIGN_ENTITLEMENTS: KeyboardExtension/KeyboardExtension.entitlements
        DEVELOPMENT_TEAM: 55YFRJ3MBY
        CODE_SIGN_STYLE: Automatic
schemes:
  BarcodeKeyboard:
    build:
      targets:
        BarcodeKeyboard: [run, test, profile, analyze, archive]
        KeyboardExtension: [run, test, profile, analyze, archive]
    run:
      config: Debug
    test:
      config: Debug
    archive:
      config: Release
  KeyboardExtension:
    build:
      targets:
        KeyboardExtension: [run, test, profile, analyze, archive]
    run:
      config: Debug
